# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotel_wifi_strength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.IntegerField(unique=True)),
                ('ean_id', models.IntegerField()),
                ('tripadvisor_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('full_address', models.TextField()),
                ('expected_speed', models.CharField(max_length=30)),
                ('percentile_rank', models.CharField(max_length=30)),
                ('confidence', models.CharField(max_length=30)),
            ],
        ),
    ]
