# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_test', '0002_tripcase_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tripcase_review',
        ),
    ]
