# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tripcase_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.IntegerField(unique=True)),
                ('star_rating', models.IntegerField()),
                ('guest_review', models.TextField()),
                ('guest_name', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=100)),
            ],
        ),
    ]
