# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripcase_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripcase_review',
            name='property_id',
            field=models.IntegerField(),
        ),
    ]
